/**
 * Hyperlink Horizon - Export API
 * Generates reports in PDF, CSV, and Markdown formats
 */

import { NextResponse } from 'next/server';
import { getAudit, getLinksForAudit, getSuggestionsForLink } from '@/lib/db';

export async function GET(request) {
    const { searchParams } = new URL(request.url);
    const auditId = searchParams.get('auditId');
    const format = searchParams.get('format') || 'json';

    if (!auditId) {
        return NextResponse.json(
            { error: 'Audit ID is required' },
            { status: 400 }
        );
    }

    // Get audit data
    const audit = getAudit(auditId);
    if (!audit) {
        return NextResponse.json(
            { error: 'Audit not found' },
            { status: 404 }
        );
    }

    // Get links and their suggestions
    const links = getLinksForAudit(auditId);
    const linksWithSuggestions = links.map(link => ({
        ...link,
        suggestions: getSuggestionsForLink(link.id),
    }));

    const data = {
        audit,
        links: linksWithSuggestions,
    };

    switch (format.toLowerCase()) {
        case 'csv':
            return exportCsv(data);
        case 'markdown':
        case 'md':
            return exportMarkdown(data);
        case 'json':
        default:
            return NextResponse.json(data);
    }
}

/**
 * Export as CSV
 */
function exportCsv(data) {
    const { audit, links } = data;

    const headers = [
        'URL',
        'Status',
        'Status Code',
        'Reason',
        'Response Time (ms)',
        'Checked At',
        'Suggestion 1',
        'Suggestion 2',
        'Suggestion 3',
    ];

    const rows = links.map(link => {
        const suggestions = link.suggestions || [];
        return [
            `"${link.original_url}"`,
            link.status,
            link.status_code || '',
            `"${link.reason || ''}"`,
            link.response_time || '',
            link.checked_at || '',
            suggestions[0]?.suggested_url || '',
            suggestions[1]?.suggested_url || '',
            suggestions[2]?.suggested_url || '',
        ].join(',');
    });

    const csv = [
        `# Hyperlink Horizon Audit Report`,
        `# File: ${audit.filename}`,
        `# Date: ${audit.created_at}`,
        `# Total Links: ${audit.total_links}`,
        '',
        headers.join(','),
        ...rows,
    ].join('\n');

    return new Response(csv, {
        headers: {
            'Content-Type': 'text/csv',
            'Content-Disposition': `attachment; filename="audit-${audit.id}.csv"`,
        },
    });
}

/**
 * Export as Markdown
 */
function exportMarkdown(data) {
    const { audit, links } = data;

    const statusEmoji = {
        working: '✅',
        broken: '❌',
        redirect: '↪️',
        restricted: '🔐',
        pending: '⏳',
    };

    let md = `# Link Audit Report

**Document:** ${audit.filename}  
**Date:** ${new Date(audit.created_at).toLocaleDateString()}  
**Total Links:** ${audit.total_links}

## Summary

| Status | Count |
|--------|-------|
| ✅ Working | ${audit.working_count} |
| ❌ Broken | ${audit.broken_count} |
| 🔐 Restricted | ${audit.restricted_count} |

## Link Details

`;

    // Group links by status
    const grouped = {
        broken: links.filter(l => l.status === 'broken'),
        restricted: links.filter(l => l.status === 'restricted'),
        redirect: links.filter(l => l.status === 'redirect'),
        working: links.filter(l => l.status === 'working'),
    };

    for (const [status, statusLinks] of Object.entries(grouped)) {
        if (statusLinks.length === 0) continue;

        md += `### ${statusEmoji[status] || ''} ${status.charAt(0).toUpperCase() + status.slice(1)} Links (${statusLinks.length})\n\n`;

        for (const link of statusLinks) {
            md += `- **${link.original_url}**\n`;

            if (link.reason) {
                md += `  - Reason: ${link.reason}\n`;
            }

            if (link.suggestions?.length > 0) {
                md += `  - **Suggested Alternatives:**\n`;
                for (const suggestion of link.suggestions) {
                    md += `    - [${suggestion.title || suggestion.suggested_url}](${suggestion.suggested_url})\n`;
                    if (suggestion.description) {
                        md += `      ${suggestion.description}\n`;
                    }
                }
            }
            md += '\n';
        }
    }

    md += `\n---\n*Generated by Hyperlink Horizon*`;

    return new Response(md, {
        headers: {
            'Content-Type': 'text/markdown',
            'Content-Disposition': `attachment; filename="audit-${audit.id}.md"`,
        },
    });
}
